In [4]:
import numpy as np
from time import process_time

In [5]:
python_list=[i for i in range(10000)]
start_time= process_time()
python_list=[i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.00336367599999976


In [12]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array +=5
end_time=process_time()
print(end_time - start_time)

0.001878959999999985


In [13]:
type(np_array)

numpy.ndarray

In [14]:
a=np.array([1,2,3,4])
print(a)
a.shape

[1 2 3 4]


(4,)

In [16]:
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
x=np.ones((4,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
y=np.full((5,4),5)
print(y)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [19]:
y=np.full((5,4),0)
print(y)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [20]:
e=np.eye(5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [21]:
b=np.random.random((3,4))
print(b)

[[0.5165813  0.69390008 0.12829458 0.95817005]
 [0.56222057 0.91787816 0.72853709 0.66259254]
 [0.52362832 0.28587771 0.38462022 0.64559602]]
